### ISSUE TITLE
artiq_ctlmgr logging does not appear in artiq_gui

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#110] opened 2015-08-25 23:48 UTC
Output on artiq_ctlmgr terminal is
```bash
rabi2@vboxartiq:/media/sf_git/nistpenning/artiq$ artiq_ctlmgr
usage: novatech409b_controller [-h] [--bind BIND] [-p PORT] [-d DEVICE]
                               [--simulation] [-v] [-q]
novatech409b_controller: error: argument -p/--port: invalid int value: '#3254'
WARNING:artiq.frontend.artiq_ctlmgr:Controller novatech_a exited
WARNING:artiq.frontend.artiq_ctlmgr:Restarting in 5.0 seconds
usage: novatech409b_controller [-h] [--bind BIND] [-p PORT] [-d DEVICE]
                               [--simulation] [-v] [-q]
novatech409b_controller: error: argument -p/--port: invalid int value: '#3254'
WARNING:artiq.frontend.artiq_ctlmgr:Controller novatech_a exited
WARNING:artiq.frontend.artiq_ctlmgr:Restarting in 5.5 seconds
```
Log in GUI is empty.

**Comment by sbourdeauducq** [comment] 2015-08-26 00:55
Duplicate of #45

**Closed by sbourdeauducq** 2015-08-26 00:55 UTC
