### ISSUE TITLE
len(Scannable) support broken

### ISSUE THREAD

**Issue by jordens** [m-labs/artiq#1009] opened 2018-05-22 15:14 UTC
AFAICT this should be supported (see https://github.com/m-labs/artiq/blob/4e863b32a170eee81512ca28cb52e0b0fe83511b/artiq/language/scan.py#L84-L89)

```python
from artiq.experiment import *

class Test(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_argument("scan", Scannable(
            default=RangeScan(0, 10, 21)))

    @kernel
    def run(self):
        return len(self.scan)
```

```
old/test_len_scan.py:12:16-12:19: error: the argument of len() must be of an iterable type
        return len(self.scan)
               ^^^
old/test_len_scan.py:12:20-12:29: note: this expression has type <instance artiq.language.scan.RangeScan {
                __objectid__: numpy.int32
        }>
        return len(self.scan)
                   ^^^^^^^^^
```

**Comment by jordens** [comment] 2018-05-22 15:36
Using `self.scan.sequence` seems to be a workaround.

**Comment by whitequark** [comment] 2018-05-22 18:19
No, this isn't supposed to be supported--`len` is currently only defined for builtin types, and `__len__` is ignored.

**Comment by whitequark** [comment] 2018-05-22 18:21
This is actually a duplicate of #118.

**Comment by jordens** [comment] 2018-05-22 21:31
If `__iter__` is not supported on the core device, it should not be `portable`.

**Comment by whitequark** [comment] 2018-05-22 21:32
That predates the new compiler.

**Comment by jordens** [comment] 2018-05-22 21:34
ACK. Thanks.

**Closed** 2018-05-22 21:33 UTC
Labels: area:compiler, prio:2-normal
