### ISSUE TITLE
"unacceptable SEQ" errors on experiment load

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#732] opened 2017-05-09 11:38 UTC
Loading the below experiment causes the core device to get stuck in a TCP re-transmission loop during experiment loading. This seems to be another manifestation of #685

```python
class LargeBinary(EnvExperiment):
    def build(self):
        self.setattr_device("core")

        self.len = 4000

    def run(self):
        data = [i for i in range(self.len)]
        self.krun(data)

    @kernel
    def krun(self, data):
        self.core.reset()
        i=0
        for t in data:
            i+=t
        return i
```

Core device log in TRACE mode is [here](https://github.com/m-labs/artiq/files/986469/ttylog_only_router2.txt)
(I patched it to report the ACK sequence number. The problem still occurs with TRACE mode off).

[Packet dump](https://github.com/m-labs/artiq/files/986471/dump_only_router2.zip)

**Comment by jordens** [comment] 2017-05-11 12:33
@whitequark duplicate of #685 ?

**Comment by whitequark** [comment] 2017-05-11 14:00
> Loading the below experiment causes the core device to get stuck in a TCP re-transmission loop during experiment loading.

This is not a loop as smoltcp is making progress (just very poorly).

@jordens yes.

**Closed** 2017-05-12 00:22 UTC
Labels: area:coredevice, area:runtime, prio:3-serious

**Comment by whitequark** [comment] 2017-06-26 10:28
@cjbe As a matter of fact, with the current master the entire experiment finishes in under 100ms.
