### ISSUE TITLE
gui log scroll bar stuck at top

### ISSUE THREAD

**Issue by kgilmo** [m-labs/artiq#151] opened 2015-10-20 19:06 UTC
When buffer is getting full, the scroll bar in the log gets stuck at the top while new messages are being output.

![scrollbarstuck](https://cloud.githubusercontent.com/assets/15162088/10618130/6338a29c-772b-11e5-9ba1-8444eb381f72.png)

**Comment by sbourdeauducq** [comment] 2015-10-21 01:17
Works fine here. The scrollbar is not "stuck" at the top, I can move it down. Are you referring to being unable to view previous messages? The log is limited to the latest 1000 messages; we can easily increase that limit.

**Comment by kgilmo** [comment] 2015-10-21 04:06
Sorry, I mean 'stuck' in the sense that with incoming messages the scrollbar goes to the top which makes the most recent messages in the log difficult to read. I can move it down too, but it goes right back up immediately.

**Comment by sbourdeauducq** [comment] 2015-10-21 04:10
It works correctly here with both pyqt4 and pyqt5.

**Comment by sbourdeauducq** [comment] 2015-10-21 04:13
Is the scrollbar's cursor actually moving to the top when a new message arrives? Or do you just see a scrolling happening because old messages get discarded when the buffer is full?

**Comment by kgilmo** [comment] 2015-10-21 04:29
The cursor seems to be moving to the top.

**Comment by kgilmo** [comment] 2015-10-27 23:09
Joe sees this too in today's build of ARTIQ. Do you have a scenario that produces 1000's of lines of log content when you try to reproduce what we observe?

**Comment by kgilmo** [comment] 2015-10-27 23:12
![untitled](https://cloud.githubusercontent.com/assets/15162088/10775433/de825568-7ccd-11e5-8d9d-b6386dac93aa.png)

**Comment by sbourdeauducq** [comment] 2015-10-28 01:30
Yes, I wrote an experiment that printed a new message every couple milliseconds.

**Comment by sbourdeauducq** [comment] 2015-10-28 13:39
I can actually reproduce it on my other computer...

**Comment by sbourdeauducq** [comment] 2015-10-28 13:50
Looks like a Qt bug. It happens even when ARTIQ doesn't touch the scrolling...

**Comment by jboulder** [comment] 2015-10-28 14:01
How about trimming old messages out of the log beyond whatever depth the QT
widget can handle?

**Comment by sbourdeauducq** [comment] 2015-10-28 14:02
The trimming is actually the source of the problem. When you remove row 0 of the table (which is what the current code already does to limit the log to 1000 entries), Qt intermittently scrolls to the top.

**Comment by sbourdeauducq** [comment] 2015-10-30 16:58
This is totally a Qt issue. The program below also has the problem. Seems to be triggered by switching the window focus.


```python
import sys
from PyQt5 import QtCore, QtWidgets


class _Scroller(QtCore.QAbstractTableModel):
    def __init__(self, parent):
        QtCore.QAbstractTableModel.__init__(self, parent)

        self.headers = ["Test"]
        self.depth = 20
        self.entries = []
        self.counter = 0

        timer = QtCore.QTimer(self)
        timer.timeout.connect(self.timer_tick)
        timer.start(100)

    def headerData(self, col, orientation, role):
        if (orientation == QtCore.Qt.Horizontal
                and role == QtCore.Qt.DisplayRole):
            return self.headers[col]
        return None

    def rowCount(self, parent):
        return len(self.entries)

    def columnCount(self, parent):
        return len(self.headers)

    def insertRows(self, position, rows=1, index=QtCore.QModelIndex()):
        self.beginInsertRows(QtCore.QModelIndex(), position, position+rows-1)
        self.endInsertRows()

    def removeRows(self, position, rows=1, index=QtCore.QModelIndex()):
        self.beginRemoveRows(QtCore.QModelIndex(), position, position+rows-1)
        self.endRemoveRows()

    def timer_tick(self):
        to_add = [self.counter]
        self.counter += 1

        nrows = len(self.entries)
        self.entries.extend(to_add)
        self.insertRows(nrows, len(to_add))
        if len(self.entries) > self.depth:
            start = len(self.entries) - self.depth
            self.entries = self.entries[start:]
            self.removeRows(0, start)

    def data(self, index, role):
        if index.isValid():
            if role == QtCore.Qt.DisplayRole:
                return str(self.entries[index.row()])


def main():
    app = QtWidgets.QApplication(sys.argv)

    w = QtWidgets.QMainWindow()
    table = QtWidgets.QTableView()
    w.setCentralWidget(table)
    w.show()

    table.setModel(_Scroller(table))

    sys.exit(app.exec_())


if __name__ == '__main__':
    main()

```

**Comment by jboulder** [comment] 2015-10-30 18:12
Where are you getting your PyQt5 with support for python 3.5? -Joe

**Closed** 2015-10-31 02:29 UTC
Labels: area:gui
