### ISSUE TITLE
Silent crash on large variable assignment in core memory

### ISSUE THREAD

**Issue by charlesbaynham** [m-labs/artiq#1349] opened 2019-08-14 11:44 UTC
# Bug Report

## One-Line Summary

Core device silently hangs when a kernel assigns a variable that's too large. 

## Issue Details

Creating a list of 32471025 `int64`s causes a silent hang on the core device. This can be recovered by `delete`ing the experiment in the ARTIQ GUI. Creating a larger list of e.g. 1E8 `int64`s causes a full crash, after which the core device and `artiq_master` must be restarted. 

### Steps to Reproduce

Execute:

```
from artiq.experiment import *


class RAMCrasher(EnvExperiment):
    '''RAMCrasher
    Assign too much RAM so that the core crashes
    '''

    def build(self):
        self.setattr_device("core")
        self.setattr_argument('hard_crash', BooleanValue(default=False))

    def run(self):

        if self.hard_crash:
            num_integers = 100000000
        else:
            # This seems to be around the threshold
            num_integers = 32471025

        dt = self.make_var(num_integers)

    @kernel
    def make_var(self, size):

        size_i = int(size)

        print('Making list of int64 of size')
        print(size_i)

        start = self.core.get_rtio_counter_mu()

        variable = [int64(0)] * size_i

        end = self.core.get_rtio_counter_mu()

        dt = self.core.mu_to_seconds(end - start)

        # This check just confirms that the RAM actually was assigned and works
        variable[0] = (start)
        variable[-1] = (end)

        success = (variable[0] == float(start) and variable[-1] == float(end))

        if success:
            print('Success! Assignment took [s]')
            print(dt)
        else:
            print('Error in check. Failure took [s]')
            print(dt)

        if success:
            return dt
        else:
            return 0.0
```

### Expected Behavior

Success if variable fits within RAM, error message if not. 

### Actual (undesired) Behavior

* Silent crash for small variables
* Comms timeout, requiring restart for larger variables:
![image](https://user-images.githubusercontent.com/4397637/63018469-d636e280-be90-11e9-82dd-2aa5a753bdad.png)

### Your System (omit irrelevant parts)

* Operating System: Windows 10
* ARTIQ version: `ARTIQ v5.6910.5f8acb3f.beta`
* Version of the gateware and runtime loaded in the core device: ` 5.0.dev+567.g99e490f9;npl2`
* If using Conda, output of `conda list` : [conda_output.txt](https://github.com/m-labs/artiq/files/3501160/conda_output.txt)
* Hardware involved: Kasli + 2x Urukul, 2x SMA-DIO, 2xSampler, 1x Zotino

**Comment by whitequark** [comment] 2019-08-15 03:08
Duplicate of #544.

**Closed** 2019-08-15 03:15 UTC
Labels: type:duplicate
