### ISSUE TITLE
panic at ksupport/lib.rs:523:5: Exception(LoadFault)

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1975] opened 2022-10-08 05:29 UTC
https://forum.m-labs.hk/d/503-connectionreseterror-with-fresh-gateware

**Comment by dnadlinger** [comment] 2022-11-13 21:56
Can't reproduce this on a custom Oxford-local target based on defc69d9c with the below example – will need to try this using the actual builds from the reports.

```py
from artiq.experiment import *


class LED(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.a = 1

    @kernel
    def run(self):
        self.core.reset()
```

**Comment by dnadlinger** [comment] 2022-11-14 00:02
Can't reproduce on 303863980 mentioned in the forum thread on kc705_nist_clock either.

**Comment by dnadlinger** [comment] 2022-11-15 00:08
Can't reproduce on https://github.com/m-labs/artiq/commit/3d25092cbd7db5d4532df10d8d6494a490423f36 on Kasli `tester` either; thousands of `artiq_run` iterations proceed fine.

**Comment by fanmingyu212** [comment] 2022-11-17 00:17
The following configuration reproduces the problem on our kasli 2.0 (identifier `ucsb`). Our firmware and gateware version is https://github.com/m-labs/artiq/commit/9aa81e1234cfccca88970b8fa946f1001e271ce1. Our software version is https://github.com/Jayich-Lab/artiq/commit/f3bf24d37433ed0fb0912f1d1385f077f0f18065. The software commit contains a few fixes and added features on the above firmware commit, but should be compatible with the firmware version above.

I think maybe reproducibility of the bug is related to Windows? We are using python 3.10.6 on Windows 10. Do other labs who can reproduce this bug all use Windows?

**Comment by dnadlinger** [comment] 2022-11-17 03:04
@fanmingyu212 Would you mind preparing an ELF file with the dummy variable workaround as well? This does seem likely to be related to the toolchain, and I don't have a Windows box ready to test.

**Comment by fanmingyu212** [comment] 2022-11-17 03:25
I put both the working and not working kernels and ELF files in the `kernel_and_elf` folder in https://drive.google.com/drive/folders/1j8FNcPuehLIJcW65bP-SC364VKgV-iKT.

`artiq_compile` by default have `attribute_writeback` equal to `False` (https://github.com/m-labs/artiq/blob/master/artiq/frontend/artiq_compile.py#L64). With the default `False` value, it seems that the ELF files from both kernels are the same. I tried to set it to `True` and compiled again, and the ELF files are different. All the files are in the folder shared above.

**Comment by ThorstenGroh** [comment] 2022-11-17 15:01
I can reproduce the error on our Kasli system freshly flashed with ARTIQ-7.8123.3038639 and using a freshly installed conda environment with the same ARTIQ version. Running `artiq_master` both on Windows 10 and Linux (virtual machine) the error appears. More details here: [https://forum.m-labs.hk/d/503-connectionreseterror-with-fresh-gateware/9](https://forum.m-labs.hk/d/503-connectionreseterror-with-fresh-gateware/9) .
I did not try it from a NIX installation yet, does that matter?

**Comment by dnadlinger** [comment] 2022-11-17 20:30
@fanmingyu212: Thanks for the files, this it helpful. I see you are using LLD 15.0 – where are you getting that from? Is that a default package from upstream Conda? (Apologies for the basic questions; we don't use Windows for masters here in Oxford anymore.) This is not super-high in priority, but if you can see a way to easily install LLD 11 instead, would you mind giving that a quick try?

@ThorstenGroh:

> […] Linux (virtual machine) the error appears

Thanks, this is interesting to know – how are you setting up LLVM/LLD/… in the VM, and which version of them are you running?

**Comment by ThorstenGroh** [comment] 2022-11-18 16:11
@dnadlinger 
> Thanks, this is interesting to know – how are you setting up LLVM/LLD/… in the VM, and which version of them are you running?

Both on Windows and Linux I did not setup anything myself. If not preinstalled everything should then probably come via the conda install. On Windows LLVM is on version 15.0.4 (from `llvm-config --version`). On the linux virtual box it seems to be on version 14.0.6 (as returned by e.g. `llvm-cat --version`).

**Comment by fanmingyu212** [comment] 2022-11-19 00:58
@dnadlinger switching to LLD 11.1 seemingly fixed the problem. We were not using Conda (`llvmlite`) so we were using the system LLVM (which I installed the latest LLVM 15). I am not sure how this was an issue for other labs who use Conda though. Can others who also see this issue confirm whether it is fixed by using LLD 11?

**Comment by dnadlinger** [comment] 2022-11-20 17:02
@fanmingyu212 Okay, many thanks for the tests, that confirms my suspicion (and explains why it doesn't occur on Nix), which gives me a handle on reproducing the issue. Will look into fixing our codegen to avoid this issue…

**Comment by dnadlinger** [comment] 2022-11-23 02:13
Occurs on LLD 14 and 15, but not LLD 13; also on Linux/Nix. Now to actually debug what's going on here…

**Comment by dnadlinger** [comment] 2022-11-24 12:11
When building the runtime using LLD 14 (maybe even 13), also get:
```
artiq.coredevice.comm_kernel.LoadError: cannot load kernel: symbol lookup error: __artiq_personality
```

Looking into what's going on with the linker scripts/… there…

**Comment by dnadlinger** [comment] 2022-11-24 13:43
Okay, this has been a wild goose chase. My current theory (at least for the kernel-side issue, i.e. when building the firmware with LLD 11) is that LLD 14 orders the sections a different way, as .got/.got.plt are not in fact mentioned in the `kernel.ld` linker script, and this then overlaps with the protected region for the stack guard – `_sstack_guard = .;` is just plopped in at the end. Since the kernel stack starts at the end of the main RAM, we probably just need to move the guard page to the actual end of the image to fix this.

**Closed** 2022-11-24 17:07 UTC
