### ISSUE TITLE
DDS and TTL panels not showing up in Windows GUI

### ISSUE THREAD

**Issue by r-srinivas** [m-labs/artiq#372] opened 2016-04-04 22:33 UTC
I can see the DDS and TTL panels that display the status of the various DDS' and TTLs on my Linux virtual box but not on Windows. I can however, change the frequency of the DDS on windows and the updated frequency shows up on the virtual box GUI. Is there something I have to do to activate the DDS and TTL panels on windows?

**Comment by sbourdeauducq** [comment] 2016-04-05 01:15
duplicate of #39

**Closed by sbourdeauducq** 2016-04-05 01:15 UTC
