### ISSUE TITLE
serial debug mode ddstest

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#52] opened 2015-06-25 20:14 UTC
Repeated pattern is not noise. Using Penning lab test setup. 
```bash
test> clksrc 1
test> ddstest 5
readback fail on DDS 0, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 0, 0xffffffff != 0x55555555
readback fail on DDS 0, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 0, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 0, 0xffffffff != 0x00000000
readback fail on DDS 0, 0xffffffff != 0x12345678
readback fail on DDS 0, 0xffffffff != 0x87654321
readback fail on DDS 0, 0xffffffff != 0x0000ffff
readback fail on DDS 0, 0xffffffff != 0xffff0000
readback fail on DDS 0, 0xffffffff != 0x00ff00ff
readback fail on DDS 0, 0xffffffff != 0xff00ff00
readback fail on DDS 1, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 1, 0xffffffff != 0x55555555
readback fail on DDS 1, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 1, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 1, 0xffffffff != 0x00000000
readback fail on DDS 1, 0xffffffff != 0x12345678
readback fail on DDS 1, 0xffffffff != 0x87654321
readback fail on DDS 1, 0xffffffff != 0x0000ffff
readback fail on DDS 1, 0xffffffff != 0xffff0000
readback fail on DDS 1, 0xffffffff != 0x00ff00ff
readback fail on DDS 1, 0xffffffff != 0xff00ff00
readback fail on DDS 2, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 2, 0xffffffff != 0x55555555
readback fail on DDS 2, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 2, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 2, 0xffffffff != 0x00000000
readback fail on DDS 2, 0xffffffff != 0x12345678
readback fail on DDS 2, 0xffffffff != 0x87654321
readback fail on DDS 2, 0xffffffff != 0x0000ffff
readback fail on DDS 2, 0xffffffff != 0xffff0000
readback fail on DDS 2, 0xffffffff != 0x00ff00ff
readback fail on DDS 2, 0xffffffff != 0xff00ff00
readback fail on DDS 3, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 3, 0xffffffff != 0x55555555
readback fail on DDS 3, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 3, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 3, 0xffffffff != 0x00000000
readback fail on DDS 3, 0xffffffff != 0x12345678
readback fail on DDS 3, 0xffffffff != 0x87654321
readback fail on DDS 3, 0xffffffff != 0x0000ffff
readback fail on DDS 3, 0xffffffff != 0xffff0000
readback fail on DDS 3, 0xffffffff != 0x00ff00ff
readback fail on DDS 3, 0xffffffff != 0xff00ff00
readback fail on DDS 4, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 4, 0xffffffff != 0x55555555
readback fail on DDS 4, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 4, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 4, 0xffffffff != 0x00000000
readback fail on DDS 4, 0xffffffff != 0x12345678
readback fail on DDS 4, 0xffffffff != 0x87654321
readback fail on DDS 4, 0xffffffff != 0x0000ffff
readback fail on DDS 4, 0xffffffff != 0xffff0000
readback fail on DDS 4, 0xffffffff != 0x00ff00ff
readback fail on DDS 4, 0xffffffff != 0xff00ff00
readback fail on DDS 5, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 5, 0xffffffff != 0x55555555
readback fail on DDS 5, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 5, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 5, 0xffffffff != 0x00000000
readback fail on DDS 5, 0xffffffff != 0x12345678
readback fail on DDS 5, 0xffffffff != 0x87654321
readback fail on DDS 5, 0xffffffff != 0x0000ffff
readback fail on DDS 5, 0xffffffff != 0xffff0000
readback fail on DDS 5, 0xffffffff != 0x00ff00ff
readback fail on DDS 5, 0xffffffff != 0xff00ff00
readback fail on DDS 6, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 6, 0xffffffff != 0x55555555
readback fail on DDS 6, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 6, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 6, 0xffffffff != 0x00000000
readback fail on DDS 6, 0xffffffff != 0x12345678
readback fail on DDS 6, 0xffffffff != 0x87654321
readback fail on DDS 6, 0xffffffff != 0x0000ffff
readback fail on DDS 6, 0xffffffff != 0xffff0000
readback fail on DDS 6, 0xffffffff != 0x00ff00ff
readback fail on DDS 6, 0xffffffff != 0xff00ff00
readback fail on DDS 7, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 7, 0xffffffff != 0x55555555
readback fail on DDS 7, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 7, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 7, 0xffffffff != 0x00000000
readback fail on DDS 7, 0xffffffff != 0x12345678
readback fail on DDS 7, 0xffffffff != 0x87654321
readback fail on DDS 7, 0xffffffff != 0x0000ffff
readback fail on DDS 7, 0xffffffff != 0xffff0000
readback fail on DDS 7, 0xffffffff != 0x00ff00ff
readback fail on DDS 7, 0xffffffff != 0xff00ff00
readback fail on DDS 0, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 0, 0xffffffff != 0x55555555
readback fail on DDS 0, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 0, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 0, 0xffffffff != 0x00000000
readback fail on DDS 0, 0xffffffff != 0x12345678
readback fail on DDS 0, 0xffffffff != 0x87654321
readback fail on DDS 0, 0xffffffff != 0x0000ffff
readback fail on DDS 0, 0xffffffff != 0xffff0000
readback fail on DDS 0, 0xffffffff != 0x00ff00ff
readback fail on DDS 0, 0xffffffff != 0xff00ff00
readback fail on DDS 1, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 1, 0xffffffff != 0x55555555
readback fail on DDS 1, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 1, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 1, 0xffffffff != 0x00000000
readback fail on DDS 1, 0xffffffff != 0x12345678
readback fail on DDS 1, 0xffffffff != 0x87654321
readback fail on DDS 1, 0xffffffff != 0x0000ffff
readback fail on DDS 1, 0xffffffff != 0xffff0000
readback fail on DDS 1, 0xffffffff != 0x00ff00ff
readback fail on DDS 1, 0xffffffff != 0xff00ff00
readback fail on DDS 2, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 2, 0xffffffff != 0x55555555
readback fail on DDS 2, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 2, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 2, 0xffffffff != 0x00000000
readback fail on DDS 2, 0xffffffff != 0x12345678
readback fail on DDS 2, 0xffffffff != 0x87654321
readback fail on DDS 2, 0xffffffff != 0x0000ffff
readback fail on DDS 2, 0xffffffff != 0xffff0000
readback fail on DDS 2, 0xffffffff != 0x00ff00ff
readback fail on DDS 2, 0xffffffff != 0xff00ff00
readback fail on DDS 3, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 3, 0xffffffff != 0x55555555
readback fail on DDS 3, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 3, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 3, 0xffffffff != 0x00000000
readback fail on DDS 3, 0xffffffff != 0x12345678
readback fail on DDS 3, 0xffffffff != 0x87654321
readback fail on DDS 3, 0xffffffff != 0x0000ffff
readback fail on DDS 3, 0xffffffff != 0xffff0000
readback fail on DDS 3, 0xffffffff != 0x00ff00ff
readback fail on DDS 3, 0xffffffff != 0xff00ff00
readback fail on DDS 4, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 4, 0xffffffff != 0x55555555
readback fail on DDS 4, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 4, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 4, 0xffffffff != 0x00000000
readback fail on DDS 4, 0xffffffff != 0x12345678
readback fail on DDS 4, 0xffffffff != 0x87654321
readback fail on DDS 4, 0xffffffff != 0x0000ffff
readback fail on DDS 4, 0xffffffff != 0xffff0000
readback fail on DDS 4, 0xffffffff != 0x00ff00ff
readback fail on DDS 4, 0xffffffff != 0xff00ff00
readback fail on DDS 5, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 5, 0xffffffff != 0x55555555
readback fail on DDS 5, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 5, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 5, 0xffffffff != 0x00000000
readback fail on DDS 5, 0xffffffff != 0x12345678
readback fail on DDS 5, 0xffffffff != 0x87654321
readback fail on DDS 5, 0xffffffff != 0x0000ffff
readback fail on DDS 5, 0xffffffff != 0xffff0000
readback fail on DDS 5, 0xffffffff != 0x00ff00ff
readback fail on DDS 5, 0xffffffff != 0xff00ff00
readback fail on DDS 6, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 6, 0xffffffff != 0x55555555
readback fail on DDS 6, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 6, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 6, 0xffffffff != 0x00000000
readback fail on DDS 6, 0xffffffff != 0x12345678
readback fail on DDS 6, 0xffffffff != 0x87654321
readback fail on DDS 6, 0xffffffff != 0x0000ffff
readback fail on DDS 6, 0xffffffff != 0xffff0000
readback fail on DDS 6, 0xffffffff != 0x00ff00ff
readback fail on DDS 6, 0xffffffff != 0xff00ff00
readback fail on DDS 7, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 7, 0xffffffff != 0x55555555
readback fail on DDS 7, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 7, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 7, 0xffffffff != 0x00000000
readback fail on DDS 7, 0xffffffff != 0x12345678
readback fail on DDS 7, 0xffffffff != 0x87654321
readback fail on DDS 7, 0xffffffff != 0x0000ffff
readback fail on DDS 7, 0xffffffff != 0xffff0000
readback fail on DDS 7, 0xffffffff != 0x00ff00ff
readback fail on DDS 7, 0xffffffff != 0xff00ff00
readback fail on DDS 0, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 0, 0xffffffff != 0x55555555
readback fail on DDS 0, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 0, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 0, 0xffffffff != 0x00000000
readback fail on DDS 0, 0xffffffff != 0x12345678
readback fail on DDS 0, 0xffffffff != 0x87654321
readback fail on DDS 0, 0xffffffff != 0x0000ffff
readback fail on DDS 0, 0xffffffff != 0xffff0000
readback fail on DDS 0, 0xffffffff != 0x00ff00ff
readback fail on DDS 0, 0xffffffff != 0xff00ff00
readback fail on DDS 1, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 1, 0xffffffff != 0x55555555
readback fail on DDS 1, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 1, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 1, 0xffffffff != 0x00000000
readback fail on DDS 1, 0xffffffff != 0x12345678
readback fail on DDS 1, 0xffffffff != 0x87654321
readback fail on DDS 1, 0xffffffff != 0x0000ffff
readback fail on DDS 1, 0xffffffff != 0xffff0000
readback fail on DDS 1, 0xffffffff != 0x00ff00ff
readback fail on DDS 1, 0xffffffff != 0xff00ff00
readback fail on DDS 2, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 2, 0xffffffff != 0x55555555
readback fail on DDS 2, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 2, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 2, 0xffffffff != 0x00000000
readback fail on DDS 2, 0xffffffff != 0x12345678
readback fail on DDS 2, 0xffffffff != 0x87654321
readback fail on DDS 2, 0xffffffff != 0x0000ffff
readback fail on DDS 2, 0xffffffff != 0xffff0000
readback fail on DDS 2, 0xffffffff != 0x00ff00ff
readback fail on DDS 2, 0xffffffff != 0xff00ff00
readback fail on DDS 3, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 3, 0xffffffff != 0x55555555
readback fail on DDS 3, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 3, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 3, 0xffffffff != 0x00000000
readback fail on DDS 3, 0xffffffff != 0x12345678
readback fail on DDS 3, 0xffffffff != 0x87654321
readback fail on DDS 3, 0xffffffff != 0x0000ffff
readback fail on DDS 3, 0xffffffff != 0xffff0000
readback fail on DDS 3, 0xffffffff != 0x00ff00ff
readback fail on DDS 3, 0xffffffff != 0xff00ff00
readback fail on DDS 4, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 4, 0xffffffff != 0x55555555
readback fail on DDS 4, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 4, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 4, 0xffffffff != 0x00000000
readback fail on DDS 4, 0xffffffff != 0x12345678
readback fail on DDS 4, 0xffffffff != 0x87654321
readback fail on DDS 4, 0xffffffff != 0x0000ffff
readback fail on DDS 4, 0xffffffff != 0xffff0000
readback fail on DDS 4, 0xffffffff != 0x00ff00ff
readback fail on DDS 4, 0xffffffff != 0xff00ff00
readback fail on DDS 5, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 5, 0xffffffff != 0x55555555
readback fail on DDS 5, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 5, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 5, 0xffffffff != 0x00000000
readback fail on DDS 5, 0xffffffff != 0x12345678
readback fail on DDS 5, 0xffffffff != 0x87654321
readback fail on DDS 5, 0xffffffff != 0x0000ffff
readback fail on DDS 5, 0xffffffff != 0xffff0000
readback fail on DDS 5, 0xffffffff != 0x00ff00ff
readback fail on DDS 5, 0xffffffff != 0xff00ff00
readback fail on DDS 6, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 6, 0xffffffff != 0x55555555
readback fail on DDS 6, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 6, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 6, 0xffffffff != 0x00000000
readback fail on DDS 6, 0xffffffff != 0x12345678
readback fail on DDS 6, 0xffffffff != 0x87654321
readback fail on DDS 6, 0xffffffff != 0x0000ffff
readback fail on DDS 6, 0xffffffff != 0xffff0000
readback fail on DDS 6, 0xffffffff != 0x00ff00ff
readback fail on DDS 6, 0xffffffff != 0xff00ff00
readback fail on DDS 7, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 7, 0xffffffff != 0x55555555
readback fail on DDS 7, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 7, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 7, 0xffffffff != 0x00000000
readback fail on DDS 7, 0xffffffff != 0x12345678
readback fail on DDS 7, 0xffffffff != 0x87654321
readback fail on DDS 7, 0xffffffff != 0x0000ffff
readback fail on DDS 7, 0xffffffff != 0xffff0000
readback fail on DDS 7, 0xffffffff != 0x00ff00ff
readback fail on DDS 7, 0xffffffff != 0xff00ff00
readback fail on DDS 0, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 0, 0xffffffff != 0x55555555
readback fail on DDS 0, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 0, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 0, 0xffffffff != 0x00000000
readback fail on DDS 0, 0xffffffff != 0x12345678
readback fail on DDS 0, 0xffffffff != 0x87654321
readback fail on DDS 0, 0xffffffff != 0x0000ffff
readback fail on DDS 0, 0xffffffff != 0xffff0000
readback fail on DDS 0, 0xffffffff != 0x00ff00ff
readback fail on DDS 0, 0xffffffff != 0xff00ff00
readback fail on DDS 1, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 1, 0xffffffff != 0x55555555
readback fail on DDS 1, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 1, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 1, 0xffffffff != 0x00000000
readback fail on DDS 1, 0xffffffff != 0x12345678
readback fail on DDS 1, 0xffffffff != 0x87654321
readback fail on DDS 1, 0xffffffff != 0x0000ffff
readback fail on DDS 1, 0xffffffff != 0xffff0000
readback fail on DDS 1, 0xffffffff != 0x00ff00ff
readback fail on DDS 1, 0xffffffff != 0xff00ff00
readback fail on DDS 2, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 2, 0xffffffff != 0x55555555
readback fail on DDS 2, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 2, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 2, 0xffffffff != 0x00000000
readback fail on DDS 2, 0xffffffff != 0x12345678
readback fail on DDS 2, 0xffffffff != 0x87654321
readback fail on DDS 2, 0xffffffff != 0x0000ffff
readback fail on DDS 2, 0xffffffff != 0xffff0000
readback fail on DDS 2, 0xffffffff != 0x00ff00ff
readback fail on DDS 2, 0xffffffff != 0xff00ff00
readback fail on DDS 3, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 3, 0xffffffff != 0x55555555
readback fail on DDS 3, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 3, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 3, 0xffffffff != 0x00000000
readback fail on DDS 3, 0xffffffff != 0x12345678
readback fail on DDS 3, 0xffffffff != 0x87654321
readback fail on DDS 3, 0xffffffff != 0x0000ffff
readback fail on DDS 3, 0xffffffff != 0xffff0000
readback fail on DDS 3, 0xffffffff != 0x00ff00ff
readback fail on DDS 3, 0xffffffff != 0xff00ff00
readback fail on DDS 4, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 4, 0xffffffff != 0x55555555
readback fail on DDS 4, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 4, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 4, 0xffffffff != 0x00000000
readback fail on DDS 4, 0xffffffff != 0x12345678
readback fail on DDS 4, 0xffffffff != 0x87654321
readback fail on DDS 4, 0xffffffff != 0x0000ffff
readback fail on DDS 4, 0xffffffff != 0xffff0000
readback fail on DDS 4, 0xffffffff != 0x00ff00ff
readback fail on DDS 4, 0xffffffff != 0xff00ff00
readback fail on DDS 5, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 5, 0xffffffff != 0x55555555
readback fail on DDS 5, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 5, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 5, 0xffffffff != 0x00000000
readback fail on DDS 5, 0xffffffff != 0x12345678
readback fail on DDS 5, 0xffffffff != 0x87654321
readback fail on DDS 5, 0xffffffff != 0x0000ffff
readback fail on DDS 5, 0xffffffff != 0xffff0000
readback fail on DDS 5, 0xffffffff != 0x00ff00ff
readback fail on DDS 5, 0xffffffff != 0xff00ff00
readback fail on DDS 6, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 6, 0xffffffff != 0x55555555
readback fail on DDS 6, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 6, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 6, 0xffffffff != 0x00000000
readback fail on DDS 6, 0xffffffff != 0x12345678
readback fail on DDS 6, 0xffffffff != 0x87654321
readback fail on DDS 6, 0xffffffff != 0x0000ffff
readback fail on DDS 6, 0xffffffff != 0xffff0000
readback fail on DDS 6, 0xffffffff != 0x00ff00ff
readback fail on DDS 6, 0xffffffff != 0xff00ff00
readback fail on DDS 7, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 7, 0xffffffff != 0x55555555
readback fail on DDS 7, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 7, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 7, 0xffffffff != 0x00000000
readback fail on DDS 7, 0xffffffff != 0x12345678
readback fail on DDS 7, 0xffffffff != 0x87654321
readback fail on DDS 7, 0xffffffff != 0x0000ffff
readback fail on DDS 7, 0xffffffff != 0xffff0000
readback fail on DDS 7, 0xffffffff != 0x00ff00ff
readback fail on DDS 7, 0xffffffff != 0xff00ff00
readback fail on DDS 0, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 0, 0xffffffff != 0x55555555
readback fail on DDS 0, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 0, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 0, 0xffffffff != 0x00000000
readback fail on DDS 0, 0xffffffff != 0x12345678
readback fail on DDS 0, 0xffffffff != 0x87654321
readback fail on DDS 0, 0xffffffff != 0x0000ffff
readback fail on DDS 0, 0xffffffff != 0xffff0000
readback fail on DDS 0, 0xffffffff != 0x00ff00ff
readback fail on DDS 0, 0xffffffff != 0xff00ff00
readback fail on DDS 1, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 1, 0xffffffff != 0x55555555
readback fail on DDS 1, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 1, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 1, 0xffffffff != 0x00000000
readback fail on DDS 1, 0xffffffff != 0x12345678
readback fail on DDS 1, 0xffffffff != 0x87654321
readback fail on DDS 1, 0xffffffff != 0x0000ffff
readback fail on DDS 1, 0xffffffff != 0xffff0000
readback fail on DDS 1, 0xffffffff != 0x00ff00ff
readback fail on DDS 1, 0xffffffff != 0xff00ff00
readback fail on DDS 2, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 2, 0xffffffff != 0x55555555
readback fail on DDS 2, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 2, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 2, 0xffffffff != 0x00000000
readback fail on DDS 2, 0xffffffff != 0x12345678
readback fail on DDS 2, 0xffffffff != 0x87654321
readback fail on DDS 2, 0xffffffff != 0x0000ffff
readback fail on DDS 2, 0xffffffff != 0xffff0000
readback fail on DDS 2, 0xffffffff != 0x00ff00ff
readback fail on DDS 2, 0xffffffff != 0xff00ff00
readback fail on DDS 3, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 3, 0xffffffff != 0x55555555
readback fail on DDS 3, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 3, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 3, 0xffffffff != 0x00000000
readback fail on DDS 3, 0xffffffff != 0x12345678
readback fail on DDS 3, 0xffffffff != 0x87654321
readback fail on DDS 3, 0xffffffff != 0x0000ffff
readback fail on DDS 3, 0xffffffff != 0xffff0000
readback fail on DDS 3, 0xffffffff != 0x00ff00ff
readback fail on DDS 3, 0xffffffff != 0xff00ff00
readback fail on DDS 4, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 4, 0xffffffff != 0x55555555
readback fail on DDS 4, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 4, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 4, 0xffffffff != 0x00000000
readback fail on DDS 4, 0xffffffff != 0x12345678
readback fail on DDS 4, 0xffffffff != 0x87654321
readback fail on DDS 4, 0xffffffff != 0x0000ffff
readback fail on DDS 4, 0xffffffff != 0xffff0000
readback fail on DDS 4, 0xffffffff != 0x00ff00ff
readback fail on DDS 4, 0xffffffff != 0xff00ff00
readback fail on DDS 5, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 5, 0xffffffff != 0x55555555
readback fail on DDS 5, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 5, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 5, 0xffffffff != 0x00000000
readback fail on DDS 5, 0xffffffff != 0x12345678
readback fail on DDS 5, 0xffffffff != 0x87654321
readback fail on DDS 5, 0xffffffff != 0x0000ffff
readback fail on DDS 5, 0xffffffff != 0xffff0000
readback fail on DDS 5, 0xffffffff != 0x00ff00ff
readback fail on DDS 5, 0xffffffff != 0xff00ff00
readback fail on DDS 6, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 6, 0xffffffff != 0x55555555
readback fail on DDS 6, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 6, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 6, 0xffffffff != 0x00000000
readback fail on DDS 6, 0xffffffff != 0x12345678
readback fail on DDS 6, 0xffffffff != 0x87654321
readback fail on DDS 6, 0xffffffff != 0x0000ffff
readback fail on DDS 6, 0xffffffff != 0xffff0000
readback fail on DDS 6, 0xffffffff != 0x00ff00ff
readback fail on DDS 6, 0xffffffff != 0xff00ff00
readback fail on DDS 7, 0xffffffff != 0xaaaaaaaa
readback fail on DDS 7, 0xffffffff != 0x55555555
readback fail on DDS 7, 0xffffffff != 0xa5a5a5a5
readback fail on DDS 7, 0xffffffff != 0x5a5a5a5a
readback fail on DDS 7, 0xffffffff != 0x00000000
readback fail on DDS 7, 0xffffffff != 0x12345678
readback fail on DDS 7, 0xffffffff != 0x87654321
readback fail on DDS 7, 0xffffffff != 0x0000ffff
readback fail on DDS 7, 0xffffffff != 0xffff0000
readback fail on DDS 7, 0xffffffff != 0x00ff00ff
readback fail on DDS 7, 0xffffffff != 0xff00ff00

**Comment by jordens** [comment] 2015-06-25 20:18
duplicate of #38

**Closed by jordens** 2015-06-25 20:18 UTC
