### ISSUE TITLE
RJ45 10/100/1000 SFP failure if inserted when Kasli powers up

### ISSUE THREAD

**Issue by sbourdeauducq** [m-labs/artiq#1562] opened 2020-12-14 05:41 UTC
# Bug Report

## One-Line Summary

Ethernet fails if a 10/100/1000 (RGMII) SFP is already inserted when Kasli is powered on.

### Steps to Reproduce

1. Insert fs.com SFP-GB-GE-T into unpowered Kasli 2.0 flashed with ARTIQ-6.
2. Power it up 
3. Try to use Ethernet.

### Expected Behavior

Ethernet works.

### Actual (undesired) Behavior

No Ethernet link. Funnily enough, the Ethernet link LED is on when the RJ45 cable is unplugged and off when it is plugged.

Removing and reinserting the SFP with the Kasli powered up works around this bug.
Problem is not present with 1000BASE-X SFPs.
Not tested on Kasli 1.1.

**Comment by HarryMakes** [comment] 2020-12-14 08:20
Just tested on a v1.1 by flashing 6.7515.3f631c41.beta and the issue is reproducible. Am looking into the issue and trying to fix it.

**Comment by HarryMakes** [comment] 2020-12-23 01:27
Should be fixed with https://github.com/m-labs/misoc/pull/105 now, at least tested on a Kasli 2.0.

**Closed** 2020-12-23 02:43 UTC
