### ISSUE TITLE
set_result() from @kernel fails

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#77] opened 2015-07-16 18:29 UTC
```python
from artiq import *

class Test(EnvExperiment):
    """Test of saving result"""

    def build(self):
        self.attr_device("core")
        self.attr_device("pmt")

    @kernel 
    def get_counts(self):
        delay(1*ms)
        self.pmt.gate_rising(100*us)
        self.n = self.pmt.count()

    @kernel
    def set_result_in_kernel(self):
        # this fails
        self.get_counts()
        self.set_result("counts_from_kernel", 
                self.n)

    def set_result_on_master(self):
        # this works
        self.get_counts()
        self.set_result("counts_from_master", 
                self.n)

    def run(self):
        self.set_result_on_master()
        self.set_result_in_kernel()

```
```bash
rabi2@vboxartiq:/media/sf_virtualBoxSharedJake/britton/artiq_penning$ artiq_run repository/result_test.py
Traceback (most recent call last):
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/ast_body.py", line 55, in visit_expression
    visitor = getattr(self, method)
AttributeError: 'Visitor' object has no attribute '_visit_expr_Str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rabi2/anaconda3/bin/artiq_run", line 6, in <module>
    sys.exit(main())
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/frontend/artiq_run.py", line 133, in main
    return run(with_file=True)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/frontend/artiq_run.py", line 118, in run
    exp_inst.run()
  File "repository/result_test.py", line 31, in run
    self.set_result_in_kernel()
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/language/core.py", line 115, in run_on_core
    return exp.core.run(arg, ((exp,) + k_args), k_kwargs)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/coredevice/core.py", line 115, in run
    k_function, k_args, k_kwargs)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/coredevice/core.py", line 105, in compile
    binary = get_runtime_binary(self.runtime, func_def)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/__init__.py", line 5, in get_runtime_binary
    module.compile_function(func_def, dict())
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/module.py", line 54, in compile_function
    visitor.visit_statements(func_def.body)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/ast_body.py", line 263, in visit_statements
    visitor(node)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/ast_body.py", line 517, in _visit_stmt_Try
    self.visit_statements(node.body)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/ast_body.py", line 263, in visit_statements
    visitor(node)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/ast_body.py", line 321, in _visit_stmt_Expr
    self.visit_expression(node.value)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/ast_body.py", line 59, in visit_expression
    return visitor(node)
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/ast_body.py", line 187, in _visit_expr_Call
    [self.visit_expression(expr) for expr in node.args[1:]],
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/ast_body.py", line 187, in <listcomp>
    [self.visit_expression(expr) for expr in node.args[1:]],
  File "/home/rabi2/anaconda3/lib/python3.4/site-packages/artiq/py2llvm/ast_body.py", line 58, in visit_expression
    .format(node.__class__.__name__))
NotImplementedError: Unsupported node 'Str' in expression

**Comment by sbourdeauducq** [comment] 2015-07-17 08:37
Duplicate of #68

**Closed by sbourdeauducq** 2015-07-17 08:37 UTC
