### ISSUE TITLE
cross-module RPC detection issue

### ISSUE THREAD

**Issue by dleibrandt** [m-labs/artiq#384] opened 2016-04-07 22:45 UTC
I'd like to generate a random number in the kernel.  I'm trying the following code:
```
import numpy as np
import random

from artiq.experiment import *

class TestKernelMathRandom(EnvExperiment):
    """Test kernel math"""

    def build(self):
        self.setattr_device("core")
        
        print("build:")
        print(random.randint(0, 10))
        
    @kernel
    def run(self):
        print("kernel:")
        print(random.randint(0, 10))
```
It spits out an error when random is called in the kernel (but not in build):
```
root:Terminating with exception (AttributeError: type object 'module' has no attribute 'randint')
```

Of course, I could pre-generate all the random numbers I need in the build method, but that would be inconvenient.  Is there a way to do it in the kernel?

More generally, what all is available in the kernel?  Is this spelled out somewhere in the documentation?

**Comment by sbourdeauducq** [comment] 2016-04-08 01:39
The error probably has something to do with #366 and #260.

Note that this would not generate random numbers on the device, but RPC the ``randint`` function for execution on the host. If you want to actually generate on the device, e.g. for speed reasons, you have to implement your own PRNG that uses kernel or portable functions.

**Comment by sbourdeauducq** [comment] 2016-04-08 01:41
@dleibrandt actually, does the RPC work if you use ``randint`` like this:

```
from random import randint

...
    @kernel
    ...
        print(randint(0, 10))
```

**Comment by whitequark** [comment] 2016-04-08 09:02
Yes, modules are not currently supported since they do not fit well into the type system.

**Comment by sbourdeauducq** [comment] 2016-04-08 09:04
Can they be easily supported without integrating them into the type system (i.e. any module reference must be in the global namespace; putting modules in local variables, function arguments, etc. is not supported)

**Comment by whitequark** [comment] 2016-04-08 09:05
No, that's actually harder than doing it properly.

**Comment by whitequark** [comment] 2016-04-08 09:06
(Where by "properly" I mean faking an unique type for every instance of the module, instead of using the `type(module)` like it would normally happen.)

**Comment by sbourdeauducq** [comment] 2016-04-08 09:07
In this particular case, there will also be the problem of resolving the RPC at compile time.

**Comment by whitequark** [comment] 2016-04-08 09:08
I don't understand. It works if you import `randint` directly. It will also work if you do something like:
```python
class fakerandomcls:
  randint = random.randint
random = fakerandomcls()
```
which is what modules would effectively translate into under my propsal.

**Comment by whitequark** [comment] 2016-04-08 09:09
Ah wait, module functions don't receive `self`. That's more problematic then.

**Comment by sbourdeauducq** [comment] 2016-04-08 09:22
Okay, if the problem is understood and RPC works with the alternative import, we can defer this to 2.0 and say modules shall not be referenced in kernels.

**Comment by dleibrandt** [comment] 2016-04-08 21:25
@sbourdeauducq - Your alternative import statement also generates an error, but a different one:
```
root:Terminating with exception (RPCReturnValueError: type mismatch: cannot serialize 5 as None (<bound method Random.randint of <random.Random object at 0xa34c28>> has returned 5))
```

**Comment by whitequark** [comment] 2016-04-09 00:09
Oh yeah, I remember now why I didn't implement embedding modules in the first place--it is not very useful as most of the time you have to add annotations.

**Comment by sbourdeauducq** [comment] 2016-04-09 02:13
@dleibrandt 
```
def annotated_randint(...) -> TInt:
  return random.randint(...)
```

then use ``annotated_randint`` in kernels.

@whitequark can you add documentation for all these things?

**Comment by sbourdeauducq** [comment] 2016-04-27 09:09
Moved to #410 and #408.

**Closed** 2016-04-27 09:09 UTC
Labels: area:compiler, prio:2-normal
