### ISSUE TITLE
Sayma sawg.frequencyN.set() for N=1,2 broken

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#1042] opened 2018-06-01 14:07 UTC
Using build 20180530 HMC830 SAWG updatedJESD204B 38b51282226f9. Following generates sinusoid as expected.

```
from artiq.experiment import *


class SAWGTestSines(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl_sma_out")
        self.sawgs = [self.get_device("sawg"+str(i)) for i in range(8)]

    @kernel
    def run(self):
        self.core.reset()
        delay(1*ms)

        for sawg in self.sawgs:
            sawg.reset()
            delay(100*ns)
            sawg.amplitude1.set(.5)
            sawg.frequency0.set(49*MHz)
            delay(100*ns)

        while True:
            delay(0.5*ms)
            self.ttl_sma_out.pulse(0.6*ms)
```
Change frequency0 to frequency1 or frequency2 and output is noise. Scope capture of what is generated is below. 

![tek001](https://user-images.githubusercontent.com/20543958/40845015-6c6f32a6-6583-11e8-8e66-459881dc3952.png)

**Comment by sbourdeauducq** [comment] 2018-06-01 14:08
Duplicate of https://github.com/m-labs/artiq/issues/1040

**Closed by sbourdeauducq** 2018-06-01 14:08 UTC
