### ISSUE TITLE
GUI crashes when adding new applet

### ISSUE THREAD

**Issue by cjbe** [m-labs/artiq#444] opened 2016-05-25 20:47 UTC
On Windows 7 using release 1.0 the following crashes the GUI repeatably:
* Delete artiq_gui.pyon and start the GUI
* Right click in applets pane -> new applet
* Right click in applets pane -> new applet.

The GUI then crashes with the error:

```
Traceback (most recent call last):
  File "C:\Anaconda3\envs\artiq\lib\site-packages\artiq\gui\applets.py", line 291, in new
    assert uid not in self.applet_uids
AssertionError
```

**Comment by jordens** [comment] 2016-05-25 20:51
Reproducible (thanks!) duplicate of #430

**Closed by jordens** 2016-05-25 20:51 UTC
