### ISSUE TITLE
if connection to Master is open.... does idle_kernel automatically run if the Master hangs?

### ISSUE THREAD

**Issue by jboulder** [m-labs/artiq#59] opened 2015-07-02 16:09 UTC
If TCP connection is open to Master as when loading a new kernel, does idle_kernel automatically run if the Master hangs? No. SB is working on this. He's looking into using LWIP_TCP_KEEPALIVE.

**Comment by sbourdeauducq** [comment] 2015-07-03 19:08
Duplicate of #31

**Closed by sbourdeauducq** 2015-07-03 19:08 UTC
