### ISSUE TITLE
artiq_flash doesn't find Sayma binaries installed from conda package

### ISSUE THREAD

**Issue by jbqubit** [m-labs/artiq#890] opened 2018-01-12 22:49 UTC
```
$ find /home/britton/anaconda3/envs/artiq-dev/lib/python3.5/ -name "*.bit"
binaries/kc705-nist_clock/top.bit
binaries/sayma_amc-standalone/top.bit
binaries/sayma_rtm/top.bit
```
This naming scheme for the conda-distributed .bit breaks artiq_flash which assumes a hyphen... https://github.com/m-labs/artiq/blob/529033e016fffc69c20895348e037370faf78d20/artiq/frontend/artiq_flash.py#L219

Also, the name of the path is ```amc-standalone``` not ```standalone``` as in artiq_flash.py https://github.com/m-labs/artiq/blob/529033e016fffc69c20895348e037370faf78d20/artiq/frontend/artiq_flash.py#L204

**Comment by sbourdeauducq** [comment] 2018-01-13 02:50
> This naming scheme for the conda-distributed .bit breaks artiq_flash which assumes a hyphen... 
> Also, the name of the path is amc-standalone not standalone as in artiq_flash.py 

That's not what the problem is, but yes, there is a discrepancy in artiq_flash for the sayma names and paths.

**Comment by hartytp** [comment] 2018-01-14 12:07
Yes, I ran into this too. I have a PR prepared for this, just needs checking.

**Comment by sbourdeauducq** [comment] 2018-01-14 12:16
``artiq_flash`` will need a bit of refactoring to properly support Sayma and its RTM FPGA (we plan to put the bitstream in another flash partition like the runtime).

**Comment by sbourdeauducq** [comment] 2018-01-17 02:28
Fixed in https://github.com/m-labs/artiq/commit/f77aa9b78ff7d1a61417650cfd65dbc4635cca0f.

**Closed by sbourdeauducq** 2018-01-17 02:28 UTC

**Comment by jbqubit** [comment] 2018-01-17 15:43
Thanks!
